name: Spring Boot CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: be
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: be
        run: ./gradlew build -x test

      - name: Run tests
        working-directory: be
        run: ./gradlew test